[package]
name = "flutter-engine"
description = "Flutter engine embedder in rust"
version = "0.3.5"
authors = ["juju <gliheng@gmail.com>", "Sophie Tauchert <sophie@999eagle.moe>"]
keywords = ["flutter", "GUI"]
license = "MIT"
repository = "https://github.com/gliheng/flutter-rs"
readme = "crates-io.md"
edition = "2018"

[dependencies]
flutter-engine-sys = { version = "0.3.5", path = "../flutter-engine-sys" }
libc = "0.2.44"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
log = "^0.4"
priority-queue = "^0.6"
unic-locale = "^0.4"
parking_lot = "^0.10.0"