[package]
name = "flutter-engine"
description = "Flutter engine embedder in rust"
version = "0.2.1"
authors = ["juju <gliheng@gmail.com>", "Sophie Tauchert <sophie@999eagle.moe>"]
keywords = ["flutter", "GUI"]
license = "MIT"
repository = "https://github.com/gliheng/flutter-rs"
readme = "crates-io.md"
edition = "2018"

[dependencies]
flutter-engine-sys = { path = "../flutter-engine-sys" }
glfw = "^0.27"
gl = "0.11.0"
tinyfiledialogs = "3.3.5"
libc = "0.2.44"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
log = "^0.4"

[target.x86_64-unknown-linux-gnu.dependencies]
x11 = "^2.18"
