[package]
name = "flutter-download"
description = "download flutter engine for building"
version = "0.1.0"
authors = ["Bach <gliheng@foxmail.com>"]
keywords = ["flutter"]

[dependencies]
curl = { version = "0.4.19", features = ['http2'] }
dirs = "1.0.4"
unzip = "0.1.0"