[package]
name = "flutter-engine-sys"
description = "flutter engine sys crate"
version = "0.3.0"
authors = ["juju <gliheng@gmail.com>"]
keywords = ["flutter", "GUI"]
license = "MIT"
build = "build.rs"

[build-dependencies]
bindgen = "0.42.2"
flutter-download = { version = "0.3.0", path = "../flutter-download" }
